version: '3.1'
services:
  wordpress:
    image: wordpress 
    ports:
      - 8088:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: platzigift
    volumes:
      - ./platzigift:/var/www/html

  db:
    image: mysql:8.0
    ports:
      - 8886:3306
    environment:
      MYSQL_DATABASE: platzigift
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql